<template>
    <span
      class="
        text-xs
        inline-block
        py-2
        px-3
        leading-none
        text-center
        whitespace-nowrap
        align-baseline
        font-bold
        dark:bg-[#3a2434]
        bg-[#fff5f8]
        text-[#f1416c]
        rounded-md
      "
    >
      <slot />
    </span>
  </template>