<template>
    <span
      class="
        text-xs
        inline-block
        py-2
        px-3
        leading-none
        text-center
        whitespace-nowrap
        align-baseline
        font-bold
        bg-[#1b1b29]
        text-white
        rounded-md
      "
    >
      <slot />
    </span>
  </template>