<template>
    <span
      class="
        text-xs
        inline-block
        py-2
        px-3
        leading-none
        text-center
        whitespace-nowrap
        align-baseline
        font-bold
        text-[#50cd89]
        dark:bg-[#1c3238]
        bg-[#e8fff3]
        rounded-md
      "
    >
      <slot />
    </span>
  </template>