<template>
    <span
      class="
        text-xs
        inline-block
        py-2
        px-3
        leading-none
        text-center
        whitespace-nowrap
        align-baseline
        font-bold
        bg-[#2f264f]
        text-[#7239ea]
        rounded-md
      "
    >
      <slot />
    </span>
  </template>