<template>
  <span
    class="
      text-xs
      inline-block
      py-2
        px-3
      leading-none
      text-center
      whitespace-nowrap
      align-baseline
      font-bold
      bg-[#392f28]
      text-[#ffc700]
      rounded-md
    "
  >
    <slot />
  </span>
</template>