<template>
  <span
    class="
      text-xs
      inline-block
      py-2
        px-3
      leading-none
      text-center
      whitespace-nowrap
      align-baseline
      font-bold
      bg-[#f1faff]
      dark:bg-[#212e48]
      text-[#009ef7]
      rounded-md
    "
  >
    <slot />
  </span>
</template>